Error  usando template
reyes@LAPTOP-8K0JP7E1 MINGW64 ~/OneDrive/Documents/4Geek Bootcamp/vanillajs-hello (main)
$ git push origin main
Enumerating objects: 25006, done.
Counting objects: 100% (25006/25006), done.
Delta compression using up to 6 threads
Compressing objects: 100% (16409/16409), done.
Writing objects: 100% (25006/25006), 22.33 MiB | 6.46 MiB/s, done.
Total 25006 (delta 7330), reused 24992 (delta 7322), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (7330/7330), done.
remote: error: GH013: Repository rule violations found for refs/heads/main.
remote: 
remote: - GITHUB PUSH PROTECTION
remote:   —————————————————————————————————————————
remote:     Resolve the following violations before pushing again
remote:
remote:     - Push cannot contain secrets
remote:
remote:
remote:      (?) Learn how to resolve a blocked push
remote:      https://docs.github.com/code-security/secret-scanning/working-with-secret-scanning-and-push-protection/working-with-push-protection-from-the-command-line#resolving-a-blocked-push
remote:
remote:
remote:       —— GitHub SSH Private Key ————————————————————————————
remote:        locations:
remote:          - blob id: 425518a066b38d8489116505a378abd28f7bd6b8
remote:
remote:        (?) To push, remove secret from commit(s) or follow this URL to allow the secret.
remote:        https://github.com/reyesborjas/random-card-generator/security/secret-scanning/unblock-secret/2qJxBvZWGlFZIgOeuBKZTb9C6WB
remote:
remote:
remote:     ——[ WARNING ]—————————————————————————————————————————
remote:      Scan incomplete: This push was large and we didn't finish on time.
remote:      It can still contain undetected secrets.
remote:
remote:      (?) Use the following command to find the path of the detected secret(s):
remote:          git rev-list --objects --all | grep blobid
remote:     ——————————————————————————————————————————————————————
remote:
remote:
To https://github.com/reyesborjas/random-card-generator.git
 ! [remote rejected]   main -> main (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/reyesborjas/random-card-generator.git'